"""Pure, unit-testable pieces of the LoRA training command.

These are the parts of the old train_lora.ps1 that carried real logic (and were the riskiest to
verify in PowerShell): the optimizer/accelerate argument construction, the single-subset dataset
TOML, and the num_repeats derivation. Kept side-effect-free so tools/tests can assert on them.
"""
from __future__ import annotations

import math


def derive_repeats(image_count, steps, epochs, batch):
    """num_repeats from a target step count (single-subset). Mirrors train_lora.ps1:
        steps ~= images * repeats * epochs / batch
    Returns (repeats, actual_steps, fractional_deviation)."""
    repeats = max(1, round(steps * batch / (image_count * epochs)))
    actual = int(image_count * repeats * epochs / batch)
    dev = abs(actual - steps) / float(steps) if steps else 0.0
    return repeats, actual, dev


def render_single_subset_toml(cfg, data_dir, repeats):
    """The kohya dataset .toml for a single-folder (non-modular) character. Forward-slash paths;
    UTF-8 no-BOM is free in Python (the WinPS BOM bug is gone)."""
    data_fwd = str(data_dir).replace("\\", "/")
    return (
        f"# AUTO-GENERATED by `dev train` for character '{cfg['__char__']}' -- do not hand-edit.\n"
        "[general]\n"
        "shuffle_caption = true\n"
        "keep_tokens = 1\n"
        'caption_extension = ".txt"\n'
        "\n"
        "[[datasets]]\n"
        f"resolution = {cfg['resolution']}\n"
        f"batch_size = {cfg['batch']}\n"
        "enable_bucket = true\n"
        f"min_bucket_reso = {cfg['min_bucket_reso']}\n"
        f"max_bucket_reso = {cfg['max_bucket_reso']}\n"
        f"bucket_reso_steps = {cfg['bucket_reso_steps']}\n"
        "\n"
        "  [[datasets.subsets]]\n"
        f'  image_dir = "{data_fwd}"\n'
        f"  num_repeats = {repeats}\n"
    )


def optimizer_args(cfg):
    """The --optimizer_type block. Prodigy is the default (auto-tunes LR; d_coef is the knob).
    AdamW / AdaFactor are the Blackwell-safe alternatives (NOT adamw8bit). LR overrides apply to
    adamw/adafactor; prodigy LR must stay 1.0."""
    ad_lr = str(cfg["lr"]) if cfg.get("lr") else "3e-4"
    ad_unet = str(cfg["unet_lr"]) if cfg.get("unet_lr") else "3e-4"
    ad_te = str(cfg["text_encoder_lr"]) if cfg.get("text_encoder_lr") else "3e-5"
    opt = cfg["optimizer"]
    if opt == "adamw":
        return ["--optimizer_type", "AdamW",
                "--learning_rate", ad_lr, "--unet_lr", ad_unet, "--text_encoder_lr", ad_te]
    if opt == "adafactor":
        return ["--optimizer_type", "Adafactor",
                "--optimizer_args", "relative_step=False", "scale_parameter=False", "warmup_init=False",
                "--learning_rate", ad_lr, "--unet_lr", ad_unet, "--text_encoder_lr", ad_te]
    # prodigy
    return ["--optimizer_type", "prodigy",
            "--learning_rate", "1.0", "--unet_lr", "1.0", "--text_encoder_lr", "1.0",
            "--optimizer_args", "decouple=True", "weight_decay=0.01",
            f"d_coef={cfg['d_coef']}", "use_bias_correction=True", "safeguard_warmup=True"]


def build_accelerate_args(cfg, *, base, out_dir, output_name, dataset_cfg, trainer_script):
    """The full `accelerate launch ...` argument list. Returns a list[str]."""
    args = [
        "launch", "--num_cpu_threads_per_process", str(cfg["num_cpu_threads"]), trainer_script,
        "--pretrained_model_name_or_path", str(base),
        "--dataset_config", str(dataset_cfg),
        "--output_dir", str(out_dir), "--output_name", output_name,
        "--network_module", cfg["network_module"],
        "--network_dim", str(cfg["dim"]), "--network_alpha", str(cfg["alpha"]),
    ]
    args += optimizer_args(cfg)
    args += [
        "--lr_scheduler", cfg["lr_scheduler"],
        "--max_train_epochs", str(cfg["epochs"]),
        "--save_every_n_epochs", str(cfg["save_every_n_epochs"]),
        "--train_batch_size", str(cfg["batch"]),
        "--mixed_precision", cfg["mixed_precision"], "--save_precision", cfg["save_precision"],
        "--min_snr_gamma", str(cfg["min_snr_gamma"]), "--seed", str(cfg["seed"]),
    ]
    # Blackwell / 16 GB safety toggles (on by default; train.toml can disable them).
    if cfg.get("gradient_checkpointing"):
        args.append("--gradient_checkpointing")
    if cfg.get("cache_latents"):
        args.append("--cache_latents")
    if cfg.get("cache_latents_to_disk"):
        args.append("--cache_latents_to_disk")
    if cfg.get("sdpa"):
        args.append("--sdpa")
    if cfg.get("no_half_vae"):
        args.append("--no_half_vae")
    if not cfg.get("train_text_encoder"):
        args.append("--network_train_unet_only")   # 16 GB-safe default
    return args


def optimizer_desc(cfg):
    return f"prodigy d_coef={cfg['d_coef']}" if cfg["optimizer"] == "prodigy" else cfg["optimizer"]
